"""
RAG service sub-package.

All public names are re-exported from ``_core`` so that existing
imports via the facade at ``app.services.rag_service`` keep working.
"""

from app.services.rag._core import (  # noqa: F401
    _bm25_indices,
    _content_fallback,
    _ingest_queue,
    _ingest_status,
    _ingested_urls,
    _prepare_overview_context,
    _require_rag,
    assess_content_quality,
    close_chroma_client,
    delete_collections_by_urls,
    enqueue_for_ingest,
    fetch_article_text,
    generate_article_overview,
    get_bi_encoder,
    get_cross_encoder,
    get_db_cached_overview,
    get_ingest_status,
    ingest,
    ingest_worker_loop,
    init_chroma,
    is_rag_available,
    prewarm_models,
    query_cross_article,
    query_stream,
    semantic_split,
    split_into_chunks,
    stream_article_overview,
)

__all__ = [
    "is_rag_available",
    "_require_rag",
    "get_bi_encoder",
    "get_cross_encoder",
    "init_chroma",
    "prewarm_models",
    "enqueue_for_ingest",
    "get_ingest_status",
    "ingest_worker_loop",
    "ingest",
    "delete_collections_by_urls",
    "fetch_article_text",
    "assess_content_quality",
    "split_into_chunks",
    "semantic_split",
    "stream_article_overview",
    "generate_article_overview",
    "get_db_cached_overview",
    "query_stream",
    "query_cross_article",
    "_ingested_urls",
    "_ingest_queue",
    "_ingest_status",
    "_bm25_indices",
    "_content_fallback",
    "_prepare_overview_context",
]
